#!/bin/sh

#############################################################
#  ____  _____ ____ _   _ ____  _____ __  __ ___ _   _ ____  
# / ___|| ____/ ___| | | |  _ \| ____|  \/  |_ _| \ | |  _ \ 
# \___ \|  _|| |   | | | | |_) |  _| | |\/| || ||  \| | | | |
#  ___) | |__| |___| |_| |  _ <| |___| |  | || || |\  | |_| |
# |____/|_____\____|\___/|_| \_\_____|_|_ |_|___|_| \_|____/ 
#          / \  / ___|  / \  |  _ \| ____|  \/  \ \ / /      
#         / _ \| |     / _ \ | | | |  _| | |\/| |\ V /       
#        / ___ \ |___ / ___ \| |_| | |___| |  | | | |        
#       /_/   \_\____/_/   \_\____/|_____|_|  |_| |_|        
  

WPYTHON_BIN="framework/python/bin/python3"

SCRIPT_PATH_NAME="$0"

DIR_NAME="$(cd $(dirname ${SCRIPT_PATH_NAME}); pwd -P)"
SCRIPT_NAME="$(basename ${SCRIPT_PATH_NAME})"

case ${DIR_NAME} in
    */active-response/bin | */wodles*)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH="$(cd ${DIR_NAME}/../..; pwd)"
        fi

        PYTHON_SCRIPT="${DIR_NAME}/${SCRIPT_NAME}.py"
    ;;
    */bin)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH="$(cd ${DIR_NAME}/..; pwd)"
        fi

        PYTHON_SCRIPT="${WAZUH_PATH}/framework/scripts/$(echo ${SCRIPT_NAME} | sed 's/\-/_/g').py"
    ;;
     */integrations)
        if [ -z "${WAZUH_PATH}" ]; then
            WAZUH_PATH="$(cd ${DIR_NAME}/..; pwd)"
        fi

        PYTHON_SCRIPT="${DIR_NAME}/${SCRIPT_NAME}.py"
    ;;
esac


${WAZUH_PATH}/${WPYTHON_BIN} ${PYTHON_SCRIPT} "$@"
